version: '3.7'

services:
  api:
    image: cloudtechnologyoffice/ecs
    ports:
      - '8000:8080'
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      ECS_API_KEY: ${ECS_API_KEY}
      REPOSITORY_ACCESS_TOKEN: ${REPOSITORY_ACCESS_TOKEN}
      REPOSITORY_URL: ${REPOSITORY_URL}
      REPOSITORY_PROVIDER: ${REPOSITORY_PROVIDER}

      # Uncomment if AWS is in use
#      SOPS_KMS_ARN: ${SOPS_KMS_ARN}
#      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
#      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
#      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}

      # Uncomment if Azure is in use
#      SOPS_AZURE_KV: ${SOPS_AZURE_KV}
#      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
#      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
#      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}

      # Uncomment if GCP is in use
#      SOPS_GCP_KMS: ${SOPS_GCP_KMS}
#      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}