iam:
  policy:
    AdminReadOnly:
      inline_policy:
        Statement:
        - Action:
          - ec2:Get*
          - ec2:Describe*
          Effect: Allow
          Resource: '*'
        - Action:
          - networkmanager:Get*
          - networkmanager:Describe*
          Effect: Allow
          Resource: '*'
      managed_policy:
        - arn:aws:iam::aws:policy/AWSNetworkManagerReadOnlyAccess
        - arn:aws:iam::aws:policy/ReadOnlyAccess
