user_permissions: &user_permissions
    REPO_WRITE: 
        - user1

group_permissions: &group_permissions
    REPO_WRITE:
        - user2

repositories:
    teams/team-a-application-1:
        user_permissions:
            *user_permissions
        group_permissions:
            *group_permissions
        branches:
            main:
                protection:
                    type: pull-request-only
