permission_sets:
  AdministratorAccess:
    managed_policies:
    - arn: arn:aws:iam::aws:policy/AdministratorAccess
    session_duration: PT12H

  Billing:
    managed_policies:
    - arn: arn:aws:iam::aws:policy/job-function/Billing

  BillingReadOnly:
    managed_policies:
    - arn: arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess

  BudgetsReadOnly:
    managed_policies:
    - arn: arn:aws:iam::aws:policy/AWSBudgetsReadOnlyAccess

  DBAdmin:
    managed_policies:
    - arn: arn:aws:iam::aws:policy/AWSKeyManagementServicePowerUser
    - arn: arn:aws:iam::aws:policy/AmazonRDSFullAccess
    - arn: arn:aws:iam::aws:policy/AmazonRedshiftFullAccess
    - arn: arn:aws:iam::aws:policy/AmazonS3FullAccess
    - arn: arn:aws:iam::aws:policy/AmazonSNSFullAccess
    - arn: arn:aws:iam::aws:policy/SecretsManagerReadWrite
    - arn: arn:aws:iam::aws:policy/job-function/DatabaseAdministrator
    - arn: arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole

  NetworkAdminReadOnly:
    inline_policy:
      Statement:
      - Action:
        - ec2:Get*
        - ec2:Describe*
        Effect: Allow
        Resource: '*'
      - Action:
        - networkmanager:Get*
        - networkmanager:Describe*
        Effect: Allow
        Resource: '*'
      - Action:
        - cloudwatch:List*
        - cloudwatch:Get*
        - cloudwatch:Describe*
        Effect: Allow
        Resource: '*'
      - Action:
        - logs:Describe*
        - logs:Get*
        - logs:List*
        - logs:StartQuery
        - logs:StopQuery
        - logs:TestMetricFilter
        - logs:FilterLogEvents
        Effect: Allow
        Resource: '*'
      - Action:
        - events:List*
        - events:TestEventPattern
        - events:Describe*
        Effect: Allow
        Resource: '*'
      - Action: directconnect:Describe*
        Effect: Allow
        Resource: '*'
      Version: '2012-10-17'
    managed_policies:
    - arn: arn:aws:iam::aws:policy/AWSNetworkManagerReadOnlyAccess
    - arn: arn:aws:iam::aws:policy/AWSSupportAccess
    - arn: arn:aws:iam::aws:policy/ReadOnlyAccess
    session_duration: PT2H

  S3FullAccess:
    managed_policies:
    - arn: arn:aws:iam::aws:policy/AmazonS3FullAccess

  S3ReadOnly:
    managed_policies:
    - arn: arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  SystemsAdministrator:
    inline_policy:
      Statement:
      - Action:
        - ec2-instance-connect:SendSerialConsoleSSHPublicKey
        - ec2-instance-connect:SendSSHPublicKey
        - ec2-instance-connect:OpenTunnel
        - ec2-instance-connect:*
        - ec2:*
        Effect: Allow
        Resource:
        - '*'
        Sid: Statement1
      Version: '2012-10-17'
    managed_policies:
    - arn: arn:aws:iam::aws:policy/AmazonEC2FullAccess
