postgres:
  us-east-1:
    tags:
        name: "Postgres RDS"
        cost_center: common
    instance_class: db.t3.small
    engine_version: "15.3"
    username: administrator
    storagetype: gp3
    iops: null
    storagesize: 100
    max_allocated_storage: 500
    storage_encrypted: true
    backup_retention_period: 7
    monitoring_interval: 60

  us-east-2:
    tags:
        name: "Postgres RDS"
        cost_center: common
    instance_class: db.t3.small
    engine_version: "15.3"
    username: administrator
    storagetype: gp3
    iops: null
    storagesize: 100
    max_allocated_storage: 500
    storage_encrypted: true
    backup_retention_period: 7
    monitoring_interval: 60
