ec2:
  us-east-1:
    ami: ami-12345678901-east-1
    instance_profile: null
    instance_profile_policies:
      - AmazonSSMManagedInstanceCore
      - AmazonS3FullAccess
    instance_type: t3.medium
    disk_size: 50
    vpc_name: "*"
  us-east-2: {}

