group_permissions: &group_permissions
    REPO_READ:
        - user1
        - user2

user_permissions: &user_permissions
    REPO_WRITE:
        - user3


repositories:
    teams/team-b-application-1:
        user_permissions:
            *user_permissions
        group_permissions:
            *group_permissions
        branches:
            main:
                protection:
                    type: pull-request-only
